version: "3.7"

services:
  postgres:
    restart: unless-stopped
    image: postgres:14.2-alpine
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres_dev"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

volumes:
  postgres-data:
